version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: abtestdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./data:/data
    ports:
      - "5432:5432"
